// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQsvAeuGUP9bEO7ZYmLe_B5kuY1lVBUE',
    appId: '1:623766229177:web:0f42f60dc190cf899f8b68',
    messagingSenderId: '623766229177',
    projectId: 'healthsync-b8394',
    authDomain: 'healthsync-b8394.firebaseapp.com',
    storageBucket: 'healthsync-b8394.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcNQueYFiRt0gWn0yFpNYVjVJFqNH7SO0',
    appId: '1:623766229177:android:0594aeb06981ce999f8b68',
    messagingSenderId: '623766229177',
    projectId: 'healthsync-b8394',
    storageBucket: 'healthsync-b8394.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSLovMy4fDbdvG9jf24HwYG48mwYv7IXU',
    appId: '1:623766229177:ios:2f9d23a685d6f4039f8b68',
    messagingSenderId: '623766229177',
    projectId: 'healthsync-b8394',
    storageBucket: 'healthsync-b8394.firebasestorage.app',
    iosClientId: '623766229177-9hd31aqtui0ot22u0l8ki1e8o6lgkou6.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthsync',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSLovMy4fDbdvG9jf24HwYG48mwYv7IXU',
    appId: '1:623766229177:ios:2f9d23a685d6f4039f8b68',
    messagingSenderId: '623766229177',
    projectId: 'healthsync-b8394',
    storageBucket: 'healthsync-b8394.firebasestorage.app',
    iosClientId: '623766229177-9hd31aqtui0ot22u0l8ki1e8o6lgkou6.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQsvAeuGUP9bEO7ZYmLe_B5kuY1lVBUE',
    appId: '1:623766229177:web:6c822456233ff1ea9f8b68',
    messagingSenderId: '623766229177',
    projectId: 'healthsync-b8394',
    authDomain: 'healthsync-b8394.firebaseapp.com',
    storageBucket: 'healthsync-b8394.firebasestorage.app',
  );
}
